# Generated by Django 4.1.4 on 2023-04-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('restaurant_type', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('working_hours', models.CharField(max_length=25)),
                ('restaurant_price', models.IntegerField()),
            ],
        ),
    ]
