# Generated by Django 4.1.4 on 2023-04-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randRest', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
