# Generated by Django 4.1.4 on 2023-04-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randRest', '0003_restaurant_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='restaurants',
            field=models.ManyToManyField(null=True, to='randRest.restaurant'),
        ),
    ]
