# Generated by Django 4.1.4 on 2023-04-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randRest', '0005_alter_profile_restaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_rating',
            field=models.FloatField(null=True),
        ),
    ]
