# Generated by Django 4.1.4 on 2023-05-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randRest', '0006_restaurant_restaurant_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='restaurant_type',
            field=models.CharField(default='Casual Dining', max_length=20),
        ),
    ]
