# Generated by Django 4.1.4 on 2023-05-06 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randRest', '0007_profile_restaurant_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='restaurants',
        ),
    ]
